/*
 * File: app/store/Legislators.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeoCon.store.Legislators', {
    extend: 'Ext.data.Store',

    requires: [
        'GeoCon.model.Legislator'
    ],

    config: {
        groupField: 'fullTitle',
        model: 'GeoCon.model.Legislator',
        storeId: 'Legislators',
        proxy: {
            type: 'jsonp',
            extraParams: {
                apiKey: '8a341f85c657435989e75c9a83294762'
            },
            limitParam: '',
            noCache: false,
            pageParam: '',
            startParam: '',
            url: 'http://services.sunlightlabs.com/api/legislators.getList.json',
            callbackKey: 'jsonp',
            reader: {
                type: 'json',
                rootProperty: 'response.legislators',
                record: 'legislator'
            }
        }
    }
});