/*
 * File: app/view/legislator/Bio.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeoCon.view.legislator.Bio', {
    extend: 'Ext.Container',
    alias: 'widget.legislatorbio',

    config: {
        id: 'legislatorBio',
        tpl: [
            '<span class="legislator-pic" style="background-image: url(http://www.govtrack.us/data/photos/{govtrack_id}-50px.jpeg);"></span>',
            '<div class="legislator-name">',
            '<div class="title">{title} {firstname} {middlename} {lastname} ({party})</div>',
            '<div class="district">{state} {district}</div>',
            '</div>',
            '',
            '<div class="x-list-normal"><div class="x-list-header">Contact Info</div></div>',
            '<div class="legislator-info">',
            'Phone: {phone}<br />',
            'Email: {email}<br />',
            'Website: {website}',
            '</div>'
        ]
    }

});