/*
 * File: app/view/legislator/List.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeoCon.view.legislator.List', {
    extend: 'Ext.dataview.List',
    alias: 'widget.legislatorlist',

    config: {
        id: 'legislatorList',
        emptyText: 'Loading list of Legislators...',
        store: 'Legislators',
        grouped: true,
        itemTpl: [
            '<div class="legislator-list-item">',
            '<span class="legislator-pic" style="background-image: url(http://www.govtrack.us/data/photos/{govtrack_id}-50px.jpeg);"></span>',
            '{lastname}, {firstname} {middlename}',
            '</div>'
        ]
    }

});