/*
 * File: app/controller/Committee.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeoCon.controller.Committee', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#committeeList": {
                itemtap: 'onCommitteeTap'
            }
        }
    },

    onCommitteeTap: function(dataview, index, target, record, e, options) {
        Ext.Msg.confirm("Confirmation", "This link will open in a new window. Are you sure?", function(result) {
            if (result == 'yes') {
                window.location = 'http://www.govtrack.us/congress/committee.xpd?id=' + record.getId();
            }
        });
    }

});