/*
 * File: app/model/Legislator.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeoCon.model.Legislator', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'website',
                type: 'string'
            },
            {
                name: 'fax',
                type: 'string'
            },
            {
                name: 'govtrack_id',
                type: 'string'
            },
            {
                name: 'firstname',
                type: 'string'
            },
            {
                name: 'chamber',
                type: 'string'
            },
            {
                name: 'middlename',
                type: 'string'
            },
            {
                name: 'lastname',
                type: 'string'
            },
            {
                name: 'congress_office',
                type: 'string'
            },
            {
                name: 'eventful_id',
                type: 'string'
            },
            {
                name: 'phone',
                type: 'string'
            },
            {
                name: 'webform',
                type: 'string'
            },
            {
                name: 'youtube_url',
                type: 'string'
            },
            {
                name: 'nickname',
                type: 'string'
            },
            {
                name: 'gender',
                type: 'string'
            },
            {
                name: 'district',
                type: 'string'
            },
            {
                name: 'title',
                type: 'string'
            },
            {
                convert: function(v, rec) {
                    return rec.data.title === 'Rep' ? 'Representatives' : 'Senators';
                },
                name: 'fullTitle',
                type: 'string'
            },
            {
                name: 'congresspedia_url',
                type: 'string'
            },
            {
                name: 'in_office',
                type: 'boolean'
            },
            {
                name: 'senate_class',
                type: 'string'
            },
            {
                name: 'name_suffix',
                type: 'string'
            },
            {
                name: 'twitter_id',
                type: 'string'
            },
            {
                name: 'birthdate',
                type: 'string'
            },
            {
                name: 'bioguide_id',
                type: 'string'
            },
            {
                name: 'fec_id',
                type: 'string'
            },
            {
                name: 'state',
                type: 'string'
            },
            {
                name: 'crp_id',
                type: 'string'
            },
            {
                name: 'official_rss',
                type: 'string'
            },
            {
                name: 'facebook_id',
                type: 'string'
            },
            {
                name: 'party',
                type: 'string'
            },
            {
                name: 'email',
                type: 'string'
            },
            {
                name: 'votesmart_id',
                type: 'string'
            }
        ]
    }
});